export const BALANCED_OUTDOOR_AUTOMATION_CATEGORIES = [
  "[Home & Property]",
  "Cleaning & Floor Care",
  "Cleaning Supplies",
  "Air Quality & Moisture Control",
  "HVAC & Ventilation",
  "Water Damage Prevention",
  "Mold Prevention",
  "Tools & DIY",
  "Power Tools",
  "Hand Tools",
  "Home Repair",
  "Home Maintenance",
  "Home Improvement",
  "Property Maintenance",
  "Plumbing",
  "Electrical",
  "Painting & Decorating",
  "Garage & Workshop",
  "Safety & Security",
  "Home Safety",
  "Smart Home",
  "Lighting",
  "Storage & Organization",
  "Small Appliances",
  "Workwear & PPE",
  "Pest Control",
  "Apartment Living",
  "Garden & Yard Tools",

  "[Camping & Campsite]",
  "Camping Essentials & Must-Haves",
  "Tents & Shelters",
  "Tarps & Canopies",
  "Ropes Cordage & Tie-Downs",
  "Tent Stakes & Repair Kits",
  "Sleeping Bags & Camping Blankets",
  "Sleeping Pads & Air Mattresses",
  "Camping Pillows",
  "Hammocks & Accessories",
  "Camp Furniture",
  "Camping Chairs & Tables",
  "Coolers & Ice Packs",
  "Food Storage & Bear-Resistant Containers",
  "Camp Cooking & Stoves",
  "Camping Cookware & Utensils",
  "Grills & Fire Pits",
  "Fire Starters & Emergency Heat",
  "Water Bottles & Hydration",
  "Water Filters & Purification",
  "Camping Lighting & Lanterns",
  "Headlamps & Flashlights",
  "Portable Power Stations & Solar Chargers",
  "Batteries & Power Banks",
  "Car Camping & Overlanding",
  "RV & Campsite Accessories",
  "Camping Hygiene & Portable Toilets",
  "Showers & Privacy Shelters",
  "All-Season Camping Equipment",
  "Winter Camping & Cold-Weather Gear",
  "Summer Camping & Heat Protection",

  "[Cycling & Biking]",
  "Road Biking",
  "Mountain Biking",
  "Gravel Biking",
  "Commuter Biking",
  "Electric Bikes & E-Bikes",
  "BMX & Recreational Cycling",
  "Bicycles & Bike Components",
  "Bike Helmets & Protective Gear",
  "Bike Lights & Visibility",
  "Bike Locks & Security",
  "Bike Racks & Transportation",
  "Bike Bags Panniers & Storage",
  "Bike Pumps Tools & Repair Kits",
  "Cycling Hydration & Nutrition",
  "Cycling Apparel",

  "[Hiking & Trail]",
  "Hiking & Trekking",
  "Backpacking & Ultralight Gear",
  "Trail Running",
  "Hiking Gear & Trekking Poles",
  "Backpacks & Daypacks",
  "Navigation & GPS",
  "Compasses & Emergency Communication",
  "First Aid & Emergency Gear",
  "Survival Gear & Emergency Kits",
  "Knives Multi-Tools & Camp Tools",
  "Wildlife & Bear Safety",
  "Insect Protection & Mosquito Control",
  "Hiking Apparel",
  "Hiking Boots & Trail Shoes",
  "Outdoor Sandals & Water Shoes",

  "[Water & Beach]",
  "Surfing & Beach Activities",
  "Surfboards & Bodyboards",
  "Wetsuits & Rash Guards",
  "Surfboard Fins Leashes & Accessories",
  "Surfboard Storage & Transportation",
  "Beach Gear & Sun Shelters",
  "Swimming & Open-Water Swimming",
  "Snorkeling & Diving",
  "Kayaking & Canoeing",
  "Stand-Up Paddleboarding",
  "Rafting & Water Sports",
  "Life Jackets & Personal Flotation Devices",
  "Waterproof Phone Cases & Electronics Protection",
  "Fishing & Angling",
  "Fishing Rods Reels & Tackle",
  "Boating & Marine Accessories",
  "Dry Bags & Waterproof Storage",

  "[Outdoor Apparel]",
  "Outdoor Apparel & Accessories",
  "Technical Clothing",
  "Base Layers & Thermal Clothing",
  "Jackets & Outerwear",
  "Rain Jackets & Waterproof Pants",
  "Weather Protection & Rain Gear",
  "Sun Protection & UV Clothing",
  "Gloves Hats & Headwear",
  "Sunglasses & Outdoor Eyewear",
  "Trail Safety & Reflective Gear",
  "Outdoor Footwear",

  "[Outdoor Hobbies & Adventure]",
  "Climbing & Bouldering",
  "Climbing Harnesses Ropes & Safety Gear",
  "Mountaineering",
  "Skiing & Snowboarding",
  "Snowshoeing & Winter Hiking",
  "Sledding & Winter Recreation",
  "Ice Fishing",
  "Running & Outdoor Fitness",
  "Fitness Trackers & Sports Watches",
  "Binoculars & Wildlife Watching",
  "Birdwatching & Nature Observation",
  "Outdoor Photography & Camera Gear",
  "Geocaching & Exploration",
  "Disc Golf & Outdoor Games",
  "Picnic Gear & Outdoor Dining",
  "Gardening & Outdoor Hobbies",
  "Hunting & Outdoor Field Gear",
  "Equipment Repair Maintenance & Replacement Parts",
] as const;
